"""Initial migration

Revision ID: 54281c46bceb
Revises: 
Create Date: 2025-08-07 16:24:59.734428-06:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54281c46bceb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carreras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_carreras_id'), 'carreras', ['id'], unique=False)
    op.create_table('grupos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_carrera', sa.Integer(), nullable=False),
    sa.Column('cuatrimestre', sa.Integer(), nullable=False),
    sa.Column('nombre_grupo', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_carrera'], ['carreras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grupos_id'), 'grupos', ['id'], unique=False)
    op.create_table('materias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_materia', sa.String(length=255), nullable=False),
    sa.Column('id_carrera', sa.Integer(), nullable=False),
    sa.Column('cuatrimestre', sa.Integer(), nullable=False),
    sa.Column('horas_semanales', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_carrera'], ['carreras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materias_id'), 'materias', ['id'], unique=False)
    op.create_table('profesores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_empleado', sa.String(length=50), nullable=False),
    sa.Column('nombre_completo', sa.String(length=255), nullable=False),
    sa.Column('id_carrera', sa.Integer(), nullable=False),
    sa.Column('tipo_profesor', sa.Enum('PTC', 'PA', name='tipoprofesorenum'), nullable=False),
    sa.Column('disponibilidad', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['id_carrera'], ['carreras.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_empleado')
    )
    op.create_index(op.f('ix_profesores_id'), 'profesores', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('nombre_completo', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('SUPERUSUARIO', 'JEFE_CARRERA', name='rolenum'), nullable=False),
    sa.Column('id_carrera', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_carrera'], ['carreras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('horarios_generados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_grupo', sa.Integer(), nullable=False),
    sa.Column('id_materia', sa.Integer(), nullable=False),
    sa.Column('id_profesor', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Enum('LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES', 'SABADO', name='diasemanaenum'), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('version_horario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_grupo'], ['grupos.id'], ),
    sa.ForeignKeyConstraint(['id_materia'], ['materias.id'], ),
    sa.ForeignKeyConstraint(['id_profesor'], ['profesores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_horarios_generados_id'), 'horarios_generados', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_horarios_generados_id'), table_name='horarios_generados')
    op.drop_table('horarios_generados')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_profesores_id'), table_name='profesores')
    op.drop_table('profesores')
    op.drop_index(op.f('ix_materias_id'), table_name='materias')
    op.drop_table('materias')
    op.drop_index(op.f('ix_grupos_id'), table_name='grupos')
    op.drop_table('grupos')
    op.drop_index(op.f('ix_carreras_id'), table_name='carreras')
    op.drop_table('carreras')
    # ### end Alembic commands ###
